name: master

on: 
    push:
        branches:
            - master
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
      
    - name: checkout  
      uses: actions/checkout@v2
      
    - name: Setup shared libs
      run: sudo apt-get install libgbm1
    
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install dependencies
      run: npm ci

    - name: Prepare package
      run: npm run prepare

    - name: Run tests
      run: npm test

    - name: Publish
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}